/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'yujiorama' at '15/12/12 16:32' with Gradle 2.9
 *
 * @author yujiorama, @date 15/12/12 16:32
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
